# This is an appspec.yml template file for use with an EC2/On-Premises deployment in CodeDeploy.

version: 0.0
# Specify "os: linux" if this revision targets Amazon Linux
os: linux

files:
  - source: /
    destination: /home/ec2-user/drops-markets-api

file_exists_behavior: OVERWRITE

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  # During the AfterInstall deployment lifecycle event, run the commands
  #   in the script specified in "location".
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 1000
      runas: ec2-user

  # During the ApplicationStart deployment lifecycle event, run the commands
  #   in the script specified in "location".
  ApplicationStart:
    - location: scripts/app_start.sh
      timeout: 500
      runas: ec2-user
